repos:
  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        description: Run cargo clippy on files included in the commit
        entry: cargo clippy --all -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-fmt
        name: cargo fmt
        description: Run cargo fmt on files included in the commit
        entry: cargo fmt --all
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-nextest
        name: cargo nextest
        description: Run cargo nextest on files included in the commit
        entry: cargo nextest run
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-outdated
        name: cargo outdated
        description: Check for outdated dependencies
        entry: cargo outdated
        language: system
        pass_filenames: false

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@3.0.0']
        types: [markdown, toml]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        description: Detects high entropy strings that are likely to be passwords.
