repos:
  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        description: Run cargo clippy on files included in the commit
        entry: cargo clippy --all -- -D warnings
        language: system
        types: [file, rust]
        pass_filenames: false
      - id: cargo-fmt
        name: cargo fmt
        description: Run cargo fmt on files included in the commit
        entry: cargo fmt --all
        language: system
        types: [file, rust]
        pass_filenames: false
      - id: cargo-nextest
        name: cargo nextest
        description: Run cargo nextest on files included in the commit
        entry: cargo nextest run
        language: system
        types: [file, rust]
        pass_filenames: false
      - id: cargo-outdated
        name: cargo outdated
        description: Check for outdated dependencies
        entry: cargo outdated
        language: system
        types: [file, rust]
        pass_filenames: false