[workspace]
resolver = "2"
members = [
    "libs/common",
    "libs/db", "libs/messaging",
    "services/rest_service",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
