# Database configuration
database_url = "postgresql://admin:admin@localhost:5234/autogpt?sslmode=disable"  # pragma: allowlist secret
database_schema = "public"

# Server configuration
server_host = "127.0.0.1"
server_port = 8080